export const products = [
  {
    name: 'Swordfish Loin Portions',
    description:
      'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    productCode: 6336,
    imageId: 'Swordfish Loin Portions',
    imageUrl: 'http://dummyimage.com/232x100.png/dddddd/000000',
    price: 139.19,
    stock: 66,
    hasFreeShipping: true,
    discount: 30,
    categories: ['Dips, pastes and spreads'],
    region: ['Europe', 'United States'],
    payment: ['In 12 installments'],
    promotion: ['60% off'],
    rating: 3.66,
  },
  {
    name: 'Bar - Sweet And Salty Chocolate',
    description:
      'Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    productCode: 5649,
    imageId: 'Bar - Sweet And Salty Chocolate',
    imageUrl: 'http://dummyimage.com/109x100.png/ff4444/ffffff',
    price: 23.64,
    stock: 58,
    hasFreeShipping: false,
    discount: 60,
    categories: ['Desserts'],
    region: ['North America', 'Europe'],
    payment: ['In cash', 'In 6 installments', 'In 12 installments'],
    promotion: ['40% off'],
    rating: 3.71,
  },
  {
    name: 'Tea - Herbal Orange Spice',
    description:
      'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    productCode: 5799,
    imageId: 'Tea - Herbal Orange Spice',
    imageUrl: 'http://dummyimage.com/162x100.png/5fa2dd/ffffff',
    price: 361.2,
    stock: 99,
    hasFreeShipping: false,
    discount: 60,
    categories: ['Dried foods'],
    region: ['United States'],
    payment: ['In cash', 'In 6 installments'],
    promotion: ['New'],
    rating: 1.18,
  },
  {
    name: 'Bread Crumbs - Japanese Style',
    description:
      'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
    productCode: 4716,
    imageId: 'Bread Crumbs - Japanese Style',
    imageUrl: 'http://dummyimage.com/176x100.png/5fa2dd/ffffff',
    price: 89.89,
    stock: 38,
    hasFreeShipping: false,
    discount: 10,
    categories: ['Condiments'],
    region: ['Europe', 'North America'],
    payment: ['In 6 installments', 'In cash', 'In 12 installments'],
    promotion: ['60% off'],
    rating: 1.85,
  },
  {
    name: 'Beef Striploin Aaa',
    description:
      'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.',
    productCode: 6741,
    imageId: 'Beef Striploin Aaa',
    imageUrl: 'http://dummyimage.com/140x100.png/ff4444/ffffff',
    price: 55.03,
    stock: 36,
    hasFreeShipping: true,
    discount: 40,
    categories: ['Products'],
    region: ['Europe', 'United States'],
    payment: ['In cash', 'In 12 installments', 'In 6 installments'],
    promotion: ['90% off'],
    rating: 1.78,
  },
  {
    name: 'Mousse - Passion Fruit',
    description:
      'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
    productCode: 4100,
    imageId: 'Mousse - Passion Fruit',
    imageUrl: 'http://dummyimage.com/180x100.png/ff4444/ffffff',
    price: 186.21,
    stock: 7,
    hasFreeShipping: false,
    discount: 10,
    categories: ['Dried foods'],
    region: ['North America'],
    payment: ['In cash', 'In 6 installments'],
    promotion: ['New'],
    rating: 1.9,
  },
  {
    name: 'Fennel',
    description:
      'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
    productCode: 5799,
    imageId: 'Fennel',
    imageUrl: 'http://dummyimage.com/155x100.png/dddddd/000000',
    price: 191.77,
    stock: 45,
    hasFreeShipping: false,
    discount: 60,
    categories: ['Desserts'],
    region: ['North America', 'Global'],
    payment: ['In 12 installments'],
    promotion: ['10% off'],
    rating: 2.38,
  },
  {
    name: 'Apple - Macintosh',
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    productCode: 9804,
    imageId: 'Apple - Macintosh',
    imageUrl: 'http://dummyimage.com/103x100.png/dddddd/000000',
    price: 442.84,
    stock: 80,
    hasFreeShipping: true,
    discount: 30,
    categories: ['Dips, pastes and spreads'],
    region: ['North America'],
    payment: ['In 6 installments'],
    promotion: ['30% off'],
    rating: 1.42,
  },
  {
    name: 'Danishes - Mini Raspberry',
    description:
      'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
    productCode: 4405,
    imageId: 'Danishes - Mini Raspberry',
    imageUrl: 'http://dummyimage.com/149x100.png/dddddd/000000',
    price: 30.56,
    stock: 87,
    hasFreeShipping: false,
    discount: 80,
    categories: ['Dips, pastes and spreads'],
    region: ['Europe', 'Global'],
    payment: ['In 12 installments'],
    promotion: ['90% off'],
    rating: 2.09,
  },
  {
    name: 'Muffin - Bran Ind Wrpd',
    description:
      'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    productCode: 141,
    imageId: 'Muffin - Bran Ind Wrpd',
    imageUrl: 'http://dummyimage.com/192x100.png/cc0000/ffffff',
    price: 318.93,
    stock: 93,
    hasFreeShipping: false,
    discount: 40,
    categories: ['Products'],
    region: ['Europe'],
    payment: ['In 6 installments'],
    promotion: ['Special offer'],
    rating: 2.33,
  },
  {
    name: 'Island Oasis - Sweet And Sour Mix',
    description:
      'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    productCode: 2590,
    imageId: 'Island Oasis - Sweet And Sour Mix',
    imageUrl: 'http://dummyimage.com/228x100.png/dddddd/000000',
    price: 143.74,
    stock: 77,
    hasFreeShipping: true,
    discount: 10,
    categories: ['Desserts'],
    region: ['Europe'],
    payment: ['In 6 installments', 'In 12 installments', 'In cash'],
    promotion: ['80% off'],
    rating: 3.35,
  },
  {
    name: 'Sauce - Soya, Light',
    description:
      'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
    productCode: 4326,
    imageId: 'Sauce - Soya, Light',
    imageUrl: 'http://dummyimage.com/114x100.png/5fa2dd/ffffff',
    price: 401.61,
    stock: 29,
    hasFreeShipping: false,
    discount: 70,
    categories: ['Fast food'],
    region: ['United States', 'Global'],
    payment: ['In cash', 'In 12 installments'],
    promotion: ['Special offer'],
    rating: 1.4,
  },
  {
    name: 'Bread - Corn Muffaleta Onion',
    description:
      'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    productCode: 4949,
    imageId: 'Bread - Corn Muffaleta Onion',
    imageUrl: 'http://dummyimage.com/213x100.png/dddddd/000000',
    price: 326.62,
    stock: 85,
    hasFreeShipping: true,
    discount: 30,
    categories: ['Confectionery'],
    region: ['Global', 'Europe'],
    payment: ['In 12 installments', 'In 6 installments'],
    promotion: ['20% off'],
    rating: 3.18,
  },
  {
    name: 'Pepper - Black, Whole',
    description:
      'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    productCode: 6028,
    imageId: 'Pepper - Black, Whole',
    imageUrl: 'http://dummyimage.com/117x100.png/dddddd/000000',
    price: 409.62,
    stock: 79,
    hasFreeShipping: true,
    discount: 80,
    categories: ['Confectionery'],
    region: ['North America'],
    payment: ['In cash', 'In 6 installments', 'In 12 installments'],
    promotion: ['50% off'],
    rating: 3.71,
  },
  {
    name: 'Pastry - Apple Muffins - Mini',
    description:
      'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',
    productCode: 5283,
    imageId: 'Pastry - Apple Muffins - Mini',
    imageUrl: 'http://dummyimage.com/130x100.png/cc0000/ffffff',
    price: 354.29,
    stock: 11,
    hasFreeShipping: false,
    discount: 30,
    categories: ['Convenience foods'],
    region: ['North America'],
    payment: ['In 6 installments', 'In cash', 'In 12 installments'],
    promotion: ['New'],
    rating: 1.64,
  },
  {
    name: 'Sponge Cake Mix - Chocolate',
    description:
      'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    productCode: 6211,
    imageId: 'Sponge Cake Mix - Chocolate',
    imageUrl: 'http://dummyimage.com/215x100.png/5fa2dd/ffffff',
    price: 58.49,
    stock: 9,
    hasFreeShipping: true,
    discount: 60,
    categories: ['Appetizers'],
    region: ['Europe'],
    payment: ['In 12 installments'],
    promotion: ['30% off'],
    rating: 3.34,
  },
  {
    name: 'Bagelers - Cinn / Brown',
    description:
      'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    productCode: 2486,
    imageId: 'Bagelers - Cinn / Brown',
    imageUrl: 'http://dummyimage.com/175x100.png/dddddd/000000',
    price: 291.47,
    stock: 72,
    hasFreeShipping: false,
    discount: 80,
    categories: ['Dumplings'],
    region: ['Europe', 'United States'],
    payment: ['In 6 installments'],
    promotion: ['90% off'],
    rating: 2.6,
  },
  {
    name: 'Compound - Orange',
    description:
      'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    productCode: 3890,
    imageId: 'Compound - Orange',
    imageUrl: 'http://dummyimage.com/113x100.png/ff4444/ffffff',
    price: 19.66,
    stock: 37,
    hasFreeShipping: true,
    discount: 60,
    categories: ['Condiments'],
    region: ['Global'],
    payment: ['In cash'],
    promotion: ['60% off'],
    rating: 2.09,
  },
  {
    name: 'Grapes - Green',
    description:
      'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    productCode: 3043,
    imageId: 'Grapes - Green',
    imageUrl: 'http://dummyimage.com/209x100.png/dddddd/000000',
    price: 115.06,
    stock: 24,
    hasFreeShipping: true,
    discount: 20,
    categories: ['Products'],
    region: ['Global', 'United States'],
    payment: ['In 6 installments', 'In cash', 'In 12 installments'],
    promotion: ['10% off'],
    rating: 2.75,
  },
  {
    name: 'Soup - Campbells Chili',
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
    productCode: 9622,
    imageId: 'Soup - Campbells Chili',
    imageUrl: 'http://dummyimage.com/223x100.png/ff4444/ffffff',
    price: 422.15,
    stock: 36,
    hasFreeShipping: false,
    discount: 40,
    categories: ['Confectionery'],
    region: ['Global'],
    payment: ['In 12 installments'],
    promotion: ['70% off'],
    rating: 1.06,
  },
  {
    name: 'Cabbage - Green',
    description:
      'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    productCode: 2636,
    imageId: 'Cabbage - Green',
    imageUrl: 'http://dummyimage.com/158x100.png/cc0000/ffffff',
    price: 247.18,
    stock: 4,
    hasFreeShipping: true,
    discount: 50,
    categories: ['Dumplings'],
    region: ['Global'],
    payment: ['In 6 installments', 'In 12 installments', 'In cash'],
    promotion: ['New'],
    rating: 1.7,
  },
  {
    name: 'Soap - Hand Soap',
    description:
      'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    productCode: 3840,
    imageId: 'Soap - Hand Soap',
    imageUrl: 'http://dummyimage.com/160x100.png/5fa2dd/ffffff',
    price: 352.38,
    stock: 87,
    hasFreeShipping: true,
    discount: 20,
    categories: ['Confectionery'],
    region: ['North America'],
    payment: ['In 12 installments'],
    promotion: ['40% off'],
    rating: 2.46,
  },
  {
    name: 'Everfresh Products',
    description:
      'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',
    productCode: 4032,
    imageId: 'Everfresh Products',
    imageUrl: 'http://dummyimage.com/116x100.png/dddddd/000000',
    price: 394.47,
    stock: 86,
    hasFreeShipping: true,
    discount: 20,
    categories: ['Dips, pastes and spreads'],
    region: ['Global', 'Europe'],
    payment: ['In 6 installments', 'In 12 installments', 'In cash'],
    promotion: ['30% off'],
    rating: 3.98,
  },
  {
    name: 'Sugar - Cubes',
    description:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    productCode: 5052,
    imageId: 'Sugar - Cubes',
    imageUrl: 'http://dummyimage.com/176x100.png/cc0000/ffffff',
    price: 29.78,
    stock: 78,
    hasFreeShipping: false,
    discount: 60,
    categories: ['Dips, pastes and spreads'],
    region: ['Europe', 'United States'],
    payment: ['In cash', 'In 12 installments', 'In 6 installments'],
    promotion: ['80% off'],
    rating: 1.41,
  },
  {
    name: 'Beans - Green',
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    productCode: 7,
    imageId: 'Beans - Green',
    imageUrl: 'http://dummyimage.com/122x100.png/ff4444/ffffff',
    price: 252.13,
    stock: 67,
    hasFreeShipping: true,
    discount: 20,
    categories: ['Dried foods'],
    region: ['North America'],
    payment: ['In cash', 'In 12 installments', 'In 6 installments'],
    promotion: ['40% off'],
    rating: 1.37,
  },
  {
    name: 'Bag - Regular Kraft 20 Lb',
    description:
      'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
    productCode: 5811,
    imageId: 'Bag - Regular Kraft 20 Lb',
    imageUrl: 'http://dummyimage.com/227x100.png/cc0000/ffffff',
    price: 106.47,
    stock: 70,
    hasFreeShipping: false,
    discount: 50,
    categories: ['Products'],
    region: ['Global'],
    payment: ['In 12 installments'],
    promotion: ['Special offer'],
    rating: 2.33,
  },
  {
    name: 'Mix - Cappucino Cocktail',
    description:
      'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    productCode: 4422,
    imageId: 'Mix - Cappucino Cocktail',
    imageUrl: 'http://dummyimage.com/184x100.png/cc0000/ffffff',
    price: 73.01,
    stock: 45,
    hasFreeShipping: true,
    discount: 90,
    categories: ['Dumplings'],
    region: ['Global', 'United States'],
    payment: ['In 12 installments', 'In cash'],
    promotion: ['10% off'],
    rating: 3.94,
  },
  {
    name: 'Cheese - Brie, Triple Creme',
    description:
      'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    productCode: 6155,
    imageId: 'Cheese - Brie, Triple Creme',
    imageUrl: 'http://dummyimage.com/175x100.png/dddddd/000000',
    price: 414.03,
    stock: 75,
    hasFreeShipping: false,
    discount: 30,
    categories: ['Fast food'],
    region: ['Global'],
    payment: ['In 12 installments', 'In cash'],
    promotion: ['New'],
    rating: 2.42,
  },
  {
    name: 'Cheese - Colby',
    description:
      'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
    productCode: 7390,
    imageId: 'Cheese - Colby',
    imageUrl: 'http://dummyimage.com/157x100.png/dddddd/000000',
    price: 88.49,
    stock: 79,
    hasFreeShipping: false,
    discount: 50,
    categories: ['Convenience foods'],
    region: ['Global'],
    payment: ['In 12 installments', 'In 6 installments', 'In cash'],
    promotion: ['10% off'],
    rating: 3.27,
  },
  {
    name: 'Chips - Doritos',
    description:
      'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.',
    productCode: 2497,
    imageId: 'Chips - Doritos',
    imageUrl: 'http://dummyimage.com/238x100.png/dddddd/000000',
    price: 57.02,
    stock: 59,
    hasFreeShipping: true,
    discount: 50,
    categories: ['Condiments'],
    region: ['Europe'],
    payment: ['In 12 installments', 'In cash'],
    promotion: ['40% off'],
    rating: 1.2,
  },
  {
    name: 'Rolled Oats',
    description:
      'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    productCode: 6936,
    imageId: 'Rolled Oats',
    imageUrl: 'http://dummyimage.com/139x100.png/5fa2dd/ffffff',
    price: 4.3,
    stock: 66,
    hasFreeShipping: true,
    discount: 90,
    categories: ['Fast food'],
    region: ['Europe'],
    payment: ['In 12 installments', 'In cash'],
    promotion: ['60% off'],
    rating: 3.43,
  },
  {
    name: 'Appetizer - Mini Egg Roll, Shrimp',
    description:
      'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
    productCode: 2227,
    imageId: 'Appetizer - Mini Egg Roll, Shrimp',
    imageUrl: 'http://dummyimage.com/165x100.png/5fa2dd/ffffff',
    price: 454.09,
    stock: 37,
    hasFreeShipping: false,
    discount: 40,
    categories: ['Dips, pastes and spreads'],
    region: ['Global'],
    payment: ['In cash', 'In 12 installments'],
    promotion: ['20% off'],
    rating: 2.7,
  },
  {
    name: 'English Muffin',
    description:
      'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    productCode: 6421,
    imageId: 'English Muffin',
    imageUrl: 'http://dummyimage.com/188x100.png/cc0000/ffffff',
    price: 237.74,
    stock: 48,
    hasFreeShipping: false,
    discount: 90,
    categories: ['Confectionery'],
    region: ['United States'],
    payment: ['In 6 installments'],
    promotion: ['30% off'],
    rating: 1.34,
  },
  {
    name: 'Allspice - Jamaican',
    description:
      'Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    productCode: 9326,
    imageId: 'Allspice - Jamaican',
    imageUrl: 'http://dummyimage.com/218x100.png/5fa2dd/ffffff',
    price: 433.68,
    stock: 89,
    hasFreeShipping: false,
    discount: 80,
    categories: ['Fast food'],
    region: ['Europe', 'United States'],
    payment: ['In 6 installments', 'In 12 installments'],
    promotion: ['50% off'],
    rating: 2.39,
  },
  {
    name: 'Cheese - Gorgonzola',
    description:
      'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    productCode: 2242,
    imageId: 'Cheese - Gorgonzola',
    imageUrl: 'http://dummyimage.com/223x100.png/ff4444/ffffff',
    price: 245.62,
    stock: 63,
    hasFreeShipping: false,
    discount: 80,
    categories: ['Fast food'],
    region: ['Global'],
    payment: ['In 6 installments', 'In cash'],
    promotion: ['30% off'],
    rating: 1.43,
  },
  {
    name: 'Clam Nectar',
    description:
      'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',
    productCode: 220,
    imageId: 'Clam Nectar',
    imageUrl: 'http://dummyimage.com/151x100.png/cc0000/ffffff',
    price: 423.26,
    stock: 49,
    hasFreeShipping: false,
    discount: 90,
    categories: ['Dips, pastes and spreads'],
    region: ['Global', 'North America'],
    payment: ['In 12 installments', 'In 6 installments'],
    promotion: ['Special offer'],
    rating: 1.1,
  },
  {
    name: 'Quail - Jumbo',
    description:
      'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    productCode: 6490,
    imageId: 'Quail - Jumbo',
    imageUrl: 'http://dummyimage.com/229x100.png/dddddd/000000',
    price: 285.89,
    stock: 18,
    hasFreeShipping: false,
    discount: 80,
    categories: ['Products'],
    region: ['United States'],
    payment: ['In cash'],
    promotion: ['New'],
    rating: 3.73,
  },
  {
    name: 'Halibut - Steaks',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    productCode: 531,
    imageId: 'Halibut - Steaks',
    imageUrl: 'http://dummyimage.com/120x100.png/ff4444/ffffff',
    price: 423.3,
    stock: 97,
    hasFreeShipping: true,
    discount: 40,
    categories: ['Condiments'],
    region: ['North America', 'United States'],
    payment: ['In 6 installments', 'In cash'],
    promotion: ['80% off'],
    rating: 3.2,
  },
  {
    name: 'Lid - 16 Oz And 32 Oz',
    description:
      'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    productCode: 9177,
    imageId: 'Lid - 16 Oz And 32 Oz',
    imageUrl: 'http://dummyimage.com/134x100.png/dddddd/000000',
    price: 69.61,
    stock: 58,
    hasFreeShipping: true,
    discount: 60,
    categories: ['Convenience foods'],
    region: ['United States'],
    payment: ['In 12 installments'],
    promotion: ['none'],
    rating: 2.58,
  },
  {
    name: 'Flour - Masa De Harina Mexican',
    description:
      'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
    productCode: 9707,
    imageId: 'Flour - Masa De Harina Mexican',
    imageUrl: 'http://dummyimage.com/239x100.png/ff4444/ffffff',
    price: 388.94,
    stock: 98,
    hasFreeShipping: false,
    discount: 10,
    categories: ['Dips, pastes and spreads'],
    region: ['North America'],
    payment: ['In 12 installments'],
    promotion: ['70% off'],
    rating: 2.55,
  },
  {
    name: 'The Pop Shoppe - Black Cherry',
    description:
      'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    productCode: 6578,
    imageId: 'The Pop Shoppe - Black Cherry',
    imageUrl: 'http://dummyimage.com/175x100.png/cc0000/ffffff',
    price: 66.94,
    stock: 60,
    hasFreeShipping: false,
    discount: 80,
    categories: ['Products'],
    region: ['Europe', 'North America'],
    payment: ['In cash'],
    promotion: ['30% off'],
    rating: 2.61,
  },
  {
    name: 'Sauce - Soya, Dark',
    description:
      'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    productCode: 1294,
    imageId: 'Sauce - Soya, Dark',
    imageUrl: 'http://dummyimage.com/123x100.png/5fa2dd/ffffff',
    price: 370.84,
    stock: 39,
    hasFreeShipping: true,
    discount: 90,
    categories: ['Products'],
    region: ['United States', 'Global'],
    payment: ['In cash', 'In 12 installments'],
    promotion: ['New'],
    rating: 2.77,
  },
  {
    name: 'Sugar - Splenda Sweetener',
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    productCode: 5781,
    imageId: 'Sugar - Splenda Sweetener',
    imageUrl: 'http://dummyimage.com/106x100.png/5fa2dd/ffffff',
    price: 255.97,
    stock: 62,
    hasFreeShipping: false,
    discount: 80,
    categories: ['Desserts'],
    region: ['North America', 'United States'],
    payment: ['In cash', 'In 12 installments'],
    promotion: ['10% off'],
    rating: 1.01,
  },
  {
    name: 'Foil - 4oz Custard Cup',
    description:
      'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    productCode: 7294,
    imageId: 'Foil - 4oz Custard Cup',
    imageUrl: 'http://dummyimage.com/103x100.png/5fa2dd/ffffff',
    price: 20.49,
    stock: 8,
    hasFreeShipping: true,
    discount: 40,
    categories: ['Fast food'],
    region: ['North America'],
    payment: ['In 6 installments'],
    promotion: ['60% off'],
    rating: 3.09,
  },
  {
    name: 'Wine - Gato Negro Cabernet',
    description:
      'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    productCode: 1148,
    imageId: 'Wine - Gato Negro Cabernet',
    imageUrl: 'http://dummyimage.com/214x100.png/dddddd/000000',
    price: 189.14,
    stock: 25,
    hasFreeShipping: false,
    discount: 10,
    categories: ['Convenience foods'],
    region: ['North America', 'Europe'],
    payment: ['In 6 installments', 'In 12 installments', 'In cash'],
    promotion: ['10% off'],
    rating: 3.05,
  },
  {
    name: 'Foam Dinner Plate',
    description:
      'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.',
    productCode: 7183,
    imageId: 'Foam Dinner Plate',
    imageUrl: 'http://dummyimage.com/109x100.png/ff4444/ffffff',
    price: 45.11,
    stock: 68,
    hasFreeShipping: false,
    discount: 90,
    categories: ['Condiments'],
    region: ['Global'],
    payment: ['In 6 installments', 'In 12 installments'],
    promotion: ['New'],
    rating: 3.56,
  },
  {
    name: 'Container Clear 8 Oz',
    description:
      'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    productCode: 982,
    imageId: 'Container Clear 8 Oz',
    imageUrl: 'http://dummyimage.com/121x100.png/5fa2dd/ffffff',
    price: 246.8,
    stock: 33,
    hasFreeShipping: true,
    discount: 10,
    categories: ['Fast food'],
    region: ['Europe'],
    payment: ['In 6 installments', 'In cash'],
    promotion: ['50% off'],
    rating: 2.68,
  },
  {
    name: 'Cassis',
    description:
      'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
    productCode: 5824,
    imageId: 'Cassis',
    imageUrl: 'http://dummyimage.com/115x100.png/cc0000/ffffff',
    price: 261.05,
    stock: 4,
    hasFreeShipping: true,
    discount: 40,
    categories: ['Appetizers'],
    region: ['Europe'],
    payment: ['In 12 installments'],
    promotion: ['20% off'],
    rating: 3.9,
  },
  {
    name: 'Tofu - Soft',
    description:
      'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',
    productCode: 7164,
    imageId: 'Tofu - Soft',
    imageUrl: 'http://dummyimage.com/211x100.png/dddddd/000000',
    price: 117.45,
    stock: 74,
    hasFreeShipping: true,
    discount: 10,
    categories: ['Fast food'],
    region: ['Global'],
    payment: ['In 12 installments'],
    promotion: ['90% off'],
    rating: 1.01,
  },
  {
    name: 'Pasta - Orzo, Dry',
    description:
      'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
    productCode: 7671,
    imageId: 'Pasta - Orzo, Dry',
    imageUrl: 'http://dummyimage.com/250x100.png/5fa2dd/ffffff',
    price: 56.72,
    stock: 71,
    hasFreeShipping: false,
    discount: 60,
    categories: ['Dumplings'],
    region: ['Europe'],
    payment: ['In cash', 'In 12 installments'],
    promotion: ['10% off'],
    rating: 2.25,
  },
  {
    name: 'Bread - Rolls, Corn',
    description:
      'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    productCode: 2511,
    imageId: 'Bread - Rolls, Corn',
    imageUrl: 'http://dummyimage.com/206x100.png/cc0000/ffffff',
    price: 464.52,
    stock: 46,
    hasFreeShipping: true,
    discount: 40,
    categories: ['Products'],
    region: ['North America', 'Global'],
    payment: ['In cash', 'In 6 installments'],
    promotion: ['10% off'],
    rating: 3.52,
  },
  {
    name: 'Pepsi - 600ml',
    description:
      'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    productCode: 8418,
    imageId: 'Pepsi - 600ml',
    imageUrl: 'http://dummyimage.com/133x100.png/5fa2dd/ffffff',
    price: 101.34,
    stock: 95,
    hasFreeShipping: true,
    discount: 10,
    categories: ['Dips, pastes and spreads'],
    region: ['United States'],
    payment: ['In 6 installments', 'In cash'],
    promotion: ['New'],
    rating: 2.93,
  },
  {
    name: 'Lamb - Leg, Diced',
    description:
      'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',
    productCode: 3457,
    imageId: 'Lamb - Leg, Diced',
    imageUrl: 'http://dummyimage.com/137x100.png/dddddd/000000',
    price: 66.88,
    stock: 66,
    hasFreeShipping: false,
    discount: 70,
    categories: ['Desserts'],
    region: ['United States', 'North America'],
    payment: ['In cash', 'In 6 installments'],
    promotion: ['Special offer'],
    rating: 3.49,
  },
  {
    name: 'Coffee Cup 8oz 5338cd',
    description:
      'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
    productCode: 1047,
    imageId: 'Coffee Cup 8oz 5338cd',
    imageUrl: 'http://dummyimage.com/133x100.png/cc0000/ffffff',
    price: 229.79,
    stock: 21,
    hasFreeShipping: false,
    discount: 70,
    categories: ['Products'],
    region: ['Global', 'United States'],
    payment: ['In 6 installments', 'In cash', 'In 12 installments'],
    promotion: ['60% off'],
    rating: 2.25,
  },
  {
    name: 'Bread - Roll, Whole Wheat',
    description:
      'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    productCode: 1961,
    imageId: 'Bread - Roll, Whole Wheat',
    imageUrl: 'http://dummyimage.com/194x100.png/cc0000/ffffff',
    price: 320.34,
    stock: 75,
    hasFreeShipping: true,
    discount: 70,
    categories: ['Dips, pastes and spreads'],
    region: ['United States', 'Europe'],
    payment: ['In 6 installments'],
    promotion: ['40% off'],
    rating: 2.03,
  },
  {
    name: 'Sauce - Thousand Island',
    description:
      'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
    productCode: 6426,
    imageId: 'Sauce - Thousand Island',
    imageUrl: 'http://dummyimage.com/164x100.png/dddddd/000000',
    price: 260.42,
    stock: 59,
    hasFreeShipping: false,
    discount: 80,
    categories: ['Condiments'],
    region: ['Global', 'United States'],
    payment: ['In 6 installments', 'In cash', 'In 12 installments'],
    promotion: ['none'],
    rating: 2.78,
  },
  {
    name: 'Oregano - Fresh',
    description:
      'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    productCode: 4982,
    imageId: 'Oregano - Fresh',
    imageUrl: 'http://dummyimage.com/216x100.png/ff4444/ffffff',
    price: 419.72,
    stock: 84,
    hasFreeShipping: false,
    discount: 80,
    categories: ['Confectionery'],
    region: ['North America', 'Europe'],
    payment: ['In 12 installments'],
    promotion: ['30% off'],
    rating: 3.5,
  },
  {
    name: 'Straws - Cocktale',
    description:
      'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
    productCode: 5239,
    imageId: 'Straws - Cocktale',
    imageUrl: 'http://dummyimage.com/186x100.png/dddddd/000000',
    price: 313.42,
    stock: 39,
    hasFreeShipping: false,
    discount: 10,
    categories: ['Dumplings'],
    region: ['Europe'],
    payment: ['In cash', 'In 6 installments', 'In 12 installments'],
    promotion: ['90% off'],
    rating: 3.86,
  },
  {
    name: 'Lettuce - Romaine',
    description:
      'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
    productCode: 1627,
    imageId: 'Lettuce - Romaine',
    imageUrl: 'http://dummyimage.com/227x100.png/dddddd/000000',
    price: 139.05,
    stock: 67,
    hasFreeShipping: true,
    discount: 80,
    categories: ['Dried foods'],
    region: ['United States'],
    payment: ['In cash', 'In 6 installments'],
    promotion: ['30% off'],
    rating: 2.88,
  },
  {
    name: 'Fish - Artic Char, Cold Smoked',
    description:
      'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    productCode: 391,
    imageId: 'Fish - Artic Char, Cold Smoked',
    imageUrl: 'http://dummyimage.com/112x100.png/5fa2dd/ffffff',
    price: 325.43,
    stock: 31,
    hasFreeShipping: false,
    discount: 60,
    categories: ['Fast food'],
    region: ['Global'],
    payment: ['In cash', 'In 12 installments', 'In 6 installments'],
    promotion: ['10% off'],
    rating: 1.63,
  },
  {
    name: 'Cheese Cloth No 60',
    description:
      'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    productCode: 4898,
    imageId: 'Cheese Cloth No 60',
    imageUrl: 'http://dummyimage.com/195x100.png/ff4444/ffffff',
    price: 477.58,
    stock: 86,
    hasFreeShipping: true,
    discount: 90,
    categories: ['Dips, pastes and spreads'],
    region: ['Global', 'United States'],
    payment: ['In 6 installments'],
    promotion: ['60% off'],
    rating: 2.87,
  },
  {
    name: 'Lemonade - Mandarin, 591 Ml',
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    productCode: 2999,
    imageId: 'Lemonade - Mandarin, 591 Ml',
    imageUrl: 'http://dummyimage.com/165x100.png/cc0000/ffffff',
    price: 175.47,
    stock: 60,
    hasFreeShipping: false,
    discount: 30,
    categories: ['Appetizers'],
    region: ['North America'],
    payment: ['In 6 installments', 'In 12 installments', 'In cash'],
    promotion: ['90% off'],
    rating: 1.21,
  },
  {
    name: 'Creme De Cacao White',
    description:
      'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    productCode: 2185,
    imageId: 'Creme De Cacao White',
    imageUrl: 'http://dummyimage.com/150x100.png/5fa2dd/ffffff',
    price: 429.69,
    stock: 29,
    hasFreeShipping: false,
    discount: 60,
    categories: ['Products'],
    region: ['United States'],
    payment: ['In cash', 'In 6 installments'],
    promotion: ['Special offer'],
    rating: 2.37,
  },
  {
    name: 'Chicken - Thigh, Bone In',
    description:
      'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    productCode: 321,
    imageId: 'Chicken - Thigh, Bone In',
    imageUrl: 'http://dummyimage.com/138x100.png/ff4444/ffffff',
    price: 275.44,
    stock: 33,
    hasFreeShipping: false,
    discount: 90,
    categories: ['Dried foods'],
    region: ['North America'],
    payment: ['In 12 installments', 'In 6 installments'],
    promotion: ['none'],
    rating: 1.71,
  },
  {
    name: 'Pectin',
    description:
      'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    productCode: 8655,
    imageId: 'Pectin',
    imageUrl: 'http://dummyimage.com/165x100.png/5fa2dd/ffffff',
    price: 323.48,
    stock: 95,
    hasFreeShipping: true,
    discount: 60,
    categories: ['Fast food'],
    region: ['Global'],
    payment: ['In 12 installments', 'In cash', 'In 6 installments'],
    promotion: ['70% off'],
    rating: 3.0,
  },
  {
    name: 'Tuna - Salad Premix',
    description:
      'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    productCode: 2492,
    imageId: 'Tuna - Salad Premix',
    imageUrl: 'http://dummyimage.com/145x100.png/cc0000/ffffff',
    price: 465.34,
    stock: 80,
    hasFreeShipping: false,
    discount: 80,
    categories: ['Condiments'],
    region: ['Europe'],
    payment: ['In 12 installments', 'In 6 installments', 'In cash'],
    promotion: ['30% off'],
    rating: 1.0,
  },
  {
    name: 'Bread - French Baquette',
    description:
      'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    productCode: 3339,
    imageId: 'Bread - French Baquette',
    imageUrl: 'http://dummyimage.com/200x100.png/cc0000/ffffff',
    price: 6.08,
    stock: 98,
    hasFreeShipping: false,
    discount: 20,
    categories: ['Dried foods'],
    region: ['Europe', 'United States'],
    payment: ['In 12 installments', 'In cash', 'In 6 installments'],
    promotion: ['30% off'],
    rating: 1.31,
  },
  {
    name: 'Muffin - Mix - Strawberry Rhubarb',
    description:
      'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    productCode: 4638,
    imageId: 'Muffin - Mix - Strawberry Rhubarb',
    imageUrl: 'http://dummyimage.com/233x100.png/5fa2dd/ffffff',
    price: 264.65,
    stock: 62,
    hasFreeShipping: false,
    discount: 20,
    categories: ['Convenience foods'],
    region: ['Global'],
    payment: ['In 12 installments', 'In cash'],
    promotion: ['90% off'],
    rating: 3.98,
  },
  {
    name: 'Water, Tap',
    description:
      'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
    productCode: 5355,
    imageId: 'Water, Tap',
    imageUrl: 'http://dummyimage.com/222x100.png/cc0000/ffffff',
    price: 310.74,
    stock: 28,
    hasFreeShipping: true,
    discount: 10,
    categories: ['Convenience foods'],
    region: ['Europe', 'United States'],
    payment: ['In cash', 'In 12 installments', 'In 6 installments'],
    promotion: ['60% off'],
    rating: 3.22,
  },
  {
    name: 'Pepper - Scotch Bonnet',
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
    productCode: 7713,
    imageId: 'Pepper - Scotch Bonnet',
    imageUrl: 'http://dummyimage.com/203x100.png/dddddd/000000',
    price: 208.51,
    stock: 51,
    hasFreeShipping: true,
    discount: 60,
    categories: ['Appetizers'],
    region: ['Europe', 'Global'],
    payment: ['In 6 installments', 'In cash'],
    promotion: ['none'],
    rating: 3.86,
  },
  {
    name: 'Gherkin',
    description:
      'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
    productCode: 8974,
    imageId: 'Gherkin',
    imageUrl: 'http://dummyimage.com/242x100.png/5fa2dd/ffffff',
    price: 281.99,
    stock: 32,
    hasFreeShipping: false,
    discount: 10,
    categories: ['Convenience foods'],
    region: ['North America'],
    payment: ['In cash'],
    promotion: ['none'],
    rating: 2.05,
  },
  {
    name: 'Creme De Banane - Marie',
    description:
      'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
    productCode: 6147,
    imageId: 'Creme De Banane - Marie',
    imageUrl: 'http://dummyimage.com/233x100.png/dddddd/000000',
    price: 306.19,
    stock: 55,
    hasFreeShipping: false,
    discount: 10,
    categories: ['Dried foods'],
    region: ['Europe'],
    payment: ['In 6 installments'],
    promotion: ['20% off'],
    rating: 1.84,
  },
  {
    name: 'Pork - Inside',
    description:
      'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
    productCode: 4822,
    imageId: 'Pork - Inside',
    imageUrl: 'http://dummyimage.com/153x100.png/cc0000/ffffff',
    price: 131.66,
    stock: 50,
    hasFreeShipping: false,
    discount: 30,
    categories: ['Dried foods'],
    region: ['Global', 'North America'],
    payment: ['In cash', 'In 6 installments', 'In 12 installments'],
    promotion: ['Special offer'],
    rating: 2.3,
  },
  {
    name: 'Butcher Twine 4r',
    description:
      'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    productCode: 5246,
    imageId: 'Butcher Twine 4r',
    imageUrl: 'http://dummyimage.com/167x100.png/cc0000/ffffff',
    price: 194.68,
    stock: 12,
    hasFreeShipping: true,
    discount: 60,
    categories: ['Convenience foods'],
    region: ['United States', 'Global'],
    payment: ['In cash', 'In 12 installments', 'In 6 installments'],
    promotion: ['20% off'],
    rating: 3.66,
  },
  {
    name: 'Bread - Pumpernickle, Rounds',
    description:
      'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    productCode: 7432,
    imageId: 'Bread - Pumpernickle, Rounds',
    imageUrl: 'http://dummyimage.com/113x100.png/cc0000/ffffff',
    price: 440.72,
    stock: 48,
    hasFreeShipping: false,
    discount: 90,
    categories: ['Desserts'],
    region: ['United States'],
    payment: ['In cash', 'In 6 installments', 'In 12 installments'],
    promotion: ['none'],
    rating: 3.28,
  },
  {
    name: 'Chicken - Leg, Boneless',
    description:
      'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
    productCode: 6064,
    imageId: 'Chicken - Leg, Boneless',
    imageUrl: 'http://dummyimage.com/181x100.png/cc0000/ffffff',
    price: 275.5,
    stock: 99,
    hasFreeShipping: true,
    discount: 80,
    categories: ['Fast food'],
    region: ['North America', 'Europe'],
    payment: ['In cash', 'In 12 installments'],
    promotion: ['New'],
    rating: 2.06,
  },
  {
    name: 'Dill Weed - Fresh',
    description:
      'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    productCode: 3755,
    imageId: 'Dill Weed - Fresh',
    imageUrl: 'http://dummyimage.com/189x100.png/5fa2dd/ffffff',
    price: 468.96,
    stock: 78,
    hasFreeShipping: true,
    discount: 10,
    categories: ['Dips, pastes and spreads'],
    region: ['North America'],
    payment: ['In 6 installments', 'In cash'],
    promotion: ['Special offer'],
    rating: 1.83,
  },
  {
    name: 'Pate - Cognac',
    description:
      'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
    productCode: 8021,
    imageId: 'Pate - Cognac',
    imageUrl: 'http://dummyimage.com/134x100.png/dddddd/000000',
    price: 495.87,
    stock: 62,
    hasFreeShipping: true,
    discount: 40,
    categories: ['Dips, pastes and spreads'],
    region: ['United States', 'North America'],
    payment: ['In cash'],
    promotion: ['60% off'],
    rating: 3.55,
  },
  {
    name: 'Bread - Raisin Walnut Pull',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    productCode: 2272,
    imageId: 'Bread - Raisin Walnut Pull',
    imageUrl: 'http://dummyimage.com/195x100.png/dddddd/000000',
    price: 278.2,
    stock: 35,
    hasFreeShipping: false,
    discount: 50,
    categories: ['Convenience foods'],
    region: ['North America'],
    payment: ['In cash'],
    promotion: ['50% off'],
    rating: 2.19,
  },
  {
    name: 'Brandy - Orange, Mc Guiness',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.',
    productCode: 8828,
    imageId: 'Brandy - Orange, Mc Guiness',
    imageUrl: 'http://dummyimage.com/144x100.png/5fa2dd/ffffff',
    price: 176.12,
    stock: 1,
    hasFreeShipping: false,
    discount: 10,
    categories: ['Dips, pastes and spreads'],
    region: ['North America'],
    payment: ['In 6 installments'],
    promotion: ['90% off'],
    rating: 1.74,
  },
];

