export const products = [
  {
    price: 22.0,
    id: 1,
    name: 'Polenta Squares with Gorgonzola and Pine Nuts',
    imageUrl:
      '/img/shop/shop/polenta-squares-with-gorgonzola-and-pine-nuts.webp',
    hasFreeShipping: true,
    hasDiscount: true,
    discount: 50,
    stock: 34,
    promotion: ['50% off'],
    categories: ['Appetizer'],
    region: ['North America', 'Europe'],
    rating: 4.23,
    payment: ['In 12 installments', 'In 6 installments', 'In cash'],
    description:
      'Instead of crostini, try gluten-free polenta squares as the base for a variety of toppings. Creamy polenta becomes perfectly firm once chilled; it will hold its shape when sliced and seared. The result is a golden brown crust outside and a creamy, not rubbery, texture inside. We top ours with a funky Gorgonzola cheese, balsamic reduction, faintly sweet dried currants, and pine nuts. You could substitute chopped dried figs or cranberries for the currants, or come up with your own flavor combo. Try diced marinated tomato and basil, sautéed mushrooms and garlic, or more substantial shredded pork shoulder.',
  },
  {
    price: 103.25,
    id: 2,
    name: 'Maple-Sesame Cauliflower Bites',
    imageUrl: '/img/shop/shop/maple-sesame-cauliflower-bites.webp',
    hasFreeShipping: false,
    hasDiscount: false,
    discount: 0,
    stock: 53,
    promotion: [],
    categories: ['Appetizer'],
    region: ['United States', 'Europe'],
    rating: 2.56,
    payment: ['In 12 installments', 'In 6 installments', 'In cash'],
    description:
      'Chickpea flour is gluten-free, protein packed, and makes an incredibly light batter for baked cauliflower. Look for it near the other gluten-free flours at your local health food store. Tamari is a slightly thicker, wheat-free alternative to soy sauce with a more robust flavor. These bites can double as an appetizer or side dish served with grilled fish or baked chicken.',
  },
  {
    price: 77.99,
    id: 3,
    name: 'Double-Serrano Watermelon Bites',
    imageUrl: '/img/shop/shop/double-serrano-watermelon-bites.webp',
    hasFreeShipping: false,
    hasDiscount: false,
    discount: 0,
    stock: 63,
    promotion: ['Special offer'],
    categories: ['Appetizer'],
    region: ['Global'],
    rating: 3.51,
    payment: ['In 6 installments', 'In cash'],
    description:
      'These bites are a step up from classic prosciutto-wrapped melon and provide sweet, spicy, salty, tart, and meaty tastes. If you can’t find serrano ham, use prosciutto; you also can use balsamic glaze in place of pomegranate molasses.',
  },
  {
    price: 98.0,
    id: 4,
    name: 'Smoked Salmon Bites',
    imageUrl: '/img/shop/shop/smoked-salmon-bites.webp',
    hasFreeShipping: true,
    hasDiscount: false,
    discount: 0,
    stock: 35,
    promotion: [],
    categories: ['Appetizer'],
    region: ['Europe'],
    rating: 4.23,
    payment: ['In cash'],
    description:
      "If you're looking for an appetizer that will delight your guests with its gorgeous presentation and rich, delicious taste, the search stops here. These beautiful canapés start with a base of candy cane (or Chioggia) beet squares, whose alternating ruby and white rings are stunning. (You can add more color to the platter by alternating candy cane beet and golden beet slices.) The beet stays raw, so the slices are crunchy and sweet and hold up nicely. The jewel-like topping of easy-to-find salmon caviar turns what's truly a simple make-ahead nibble into an absolute work of art that'll make you the talk of your social circle.",
  },
  {
    price: 109.0,
    id: 5,
    name: 'French Onion Dip With Sweet Potato Chips',
    imageUrl: '/img/shop/shop/french-onion-dip-with-sweet-potato-chips.webp',
    hasFreeShipping: false,
    hasDiscount: false,
    discount: 0,
    stock: 19,
    promotion: [],
    categories: ['Appetizer'],
    region: ['North America'],
    rating: 5,
    payment: ['In 12 installments', 'In 6 installments'],
    description:
      'With big flavor and less heft, our healthier ode to the classic French onion dip is a delicious way to sneak in extra vegetables. Ditch the sodium-bomb seasoning packets and sour cream-and-mayonnaise–laden dip (which can pack a small meal’s worth of calories and sat fat into a single serving) for our homemade dip. And be patient with the caramelizing process—slowly sizzled onions have noteworthy sweetness and concentrated umami. And because no dip is complete without a dipper, baked sweet potatoes will satisfy your chip craving for half the calories of most bagged varieties.',
  },
  {
    price: 89.99,
    id: 6,
    name: 'Roasted Banana Bars with Browned Butter–Pecan Frosting',
    imageUrl:
      '/img/shop/shop/roasted-banana-bars-with-browned-butter–pecan-frosting.webp',
    hasFreeShipping: false,
    hasDiscount: false,
    discount: 0,
    stock: 2,
    promotion: [],
    categories: ['Dessert'],
    region: ['Global'],
    rating: 1.24,
    payment: ['In 6 installments', 'In cash'],
    description:
      'Put those ripe, speckled bananas to good use. This dish starts with roasting bananas which adds caramelized notes to their tropical sweetness. The bananas flavor the light-and-fluffy bars, which are topped with cream cheese icing and chopped pecans for the perfect amount of tanginess and crunch.',
  },
  {
    price: 25.8,
    id: 7,
    name: 'Texas Sheet Cake',
    imageUrl: '/img/shop/shop/texas-sheet-cake.webp',
    hasFreeShipping: false,
    hasDiscount: false,
    discount: 0,
    stock: 221,
    promotion: [],
    categories: ['Dessert'],
    region: ['North America', 'United States'],
    rating: 2.53,
    payment: ['In cash'],
    description:
      "This recipe uses butter and buttermilk in quantities that give it the right indulgently moist texture and rich flavor, but keep a serving's fat at just 10 grams and calories at about 300.",
  },
  {
    price: 50.0,
    id: 8,
    name: 'Espresso Crinkles',
    imageUrl: '/img/shop/shop/espresso-crinkles.webp',
    hasFreeShipping: false,
    hasDiscount: true,
    discount: 20,
    stock: 83,
    promotion: ['20% off', 'New'],
    categories: ['Dessert'],
    region: ['North America', 'United States'],
    rating: 3.12,
    payment: ['In 12 installments', 'In 6 installments'],
    description:
      'Unsweetened chocolate and instant espresso powder give depth of flavor to these sophisticated cookies. A dredge in powdered sugar before baking ensures sweetness, and also gives them a unique cracked surface and snow-covered look.',
  },
  {
    price: 40.73,
    id: 9,
    name: 'Vanilla Cheesecake with Cherry Topping',
    imageUrl: '/img/shop/shop/vanilla-cheesecake-with-cherry-topping.webp',
    hasFreeShipping: true,
    hasDiscount: false,
    discount: 0,
    stock: 55,
    promotion: ['Special offer'],
    categories: ['Dessert'],
    region: ['United States', 'Europe'],
    rating: 4.51,
    payment: ['In cash'],
    description:
      'In this rich cheesecake, we use the entire vanilla bean, so none of it is wasted: The seeds flavor the cheesecake, and the bean halves flavor the topping.',
  },
  {
    price: 90.14,
    id: 10,
    name: 'Amaretto Apple Streusel Cupcakes',
    imageUrl: '/img/shop/shop/amaretto-apple-streusel-cupcakes.webp',
    hasFreeShipping: false,
    hasDiscount: false,
    discount: 0,
    stock: 15,
    promotion: [],
    categories: ['Dessert'],
    region: ['North America', 'United States'],
    rating: 5,
    payment: ['In 6 installments', 'In cash'],
    description:
      "Top tender apple cupcakes with a sweet and crunchy topping of brown sugar and almonds, then drizzle with a powdered sugar glaze. The amaretto adds an even more distinct almond flavor to the cupcakes, but if you don't have it, you can use almond extract instead.",
  },
  {
    price: 47.8,
    id: 11,
    name: 'Salted Caramel Ice Cream',
    imageUrl: '/img/shop/shop/salted-caramel-ice-cream.webp',
    hasFreeShipping: false,
    hasDiscount: false,
    discount: 0,
    stock: 9,
    promotion: [],
    categories: ['Dessert'],
    region: ['North America', 'Europe'],
    rating: 1.11,
    payment: ['In 12 installments', 'In 6 installments', 'In cash'],
    description:
      "It's hard to beat the sweet-salty goodness of this indulgent yet light caramel ice cream. Light ice cream has evolved from its watery ice-milk days and in the Test Kitchen, we like to get creative with ingredients and flavors, but we hold fast to settling for nothing less than smooth, creamy, rich results.",
  },
  {
    price: 75.89,
    id: 12,
    name: 'Tiramisu',
    imageUrl: '/img/shop/shop/tiramisu.webp',
    hasFreeShipping: true,
    hasDiscount: false,
    discount: 0,
    stock: 39,
    promotion: [],
    categories: ['Dessert'],
    region: ['North America', 'Europe'],
    rating: 2.35,
    payment: ['In 6 installments', 'In cash'],
    description:
      "Tiramisu is Italian for 'lift me up.' And its indulgent creamy, mocha-tinged flavor is indeed uplifting. With layers of ladyfingers, coffee, mascarpone cheese, and shaved or grated chocolate, traditional tiramisu is a cross between a trifle and bread pudding. Our lightened version is less than 300 calories per serving, and makes for a sophisticated dinner-party treat.",
  },
  {
    price: 30.53,
    id: 13,
    name: 'Rum-Spiked Grilled Pineapple with Toasted Coconut',
    imageUrl:
      '/img/shop/shop/rum-spiked-grilled-pineapple-with-toasted-coconut.webp',
    hasFreeShipping: false,
    hasDiscount: false,
    discount: 0,
    stock: 390,
    promotion: ['Special offer'],
    categories: ['Dessert'],
    region: ['Global'],
    rating: 3.51,
    payment: ['In cash'],
    description:
      'Perfect for a backyard cookout with friends, just six ingredients make one delicious dessert in less than 10 minutes. Grilling caramelizes the sugars in the fruit for a light treat that is delicious on its own or served with low-fat vanilla ice cream.',
  },
  {
    price: 60.0,
    id: 14,
    name: 'Carrot Cake',
    imageUrl: '/img/shop/shop/carrot-cake.webp',
    hasFreeShipping: false,
    hasDiscount: true,
    discount: 80,
    stock: 35,
    promotion: ['80% off'],
    categories: ['Dessert'],
    region: ['Global'],
    rating: 4.44,
    payment: ['In 12 installments', 'In 6 installments', 'In cash'],
    description:
      'This lighter twist on traditional carrot cake features a tender cake packed with grated carrot, juicy pineapple, flaked coconut, and chopped pecans. Cream cheese frosting and a garnish of grated carrot tops the cake.',
  },
  {
    price: 3.0,
    id: 15,
    name: 'Chicken Sandwich',
    imageUrl: '/img/shop/shop/chicken-sandwich.webp',
    hasFreeShipping: false,
    hasDiscount: false,
    discount: 0,
    stock: 24,
    promotion: [],
    categories: ['Fast food'],
    region: ['Europe'],
    rating: 5,
    payment: ['In cash'],
    description:
      "The perfect combination of a generous portion of breaded chicken, soft bun, and tart pickles, it's enhanced by only one thing: Polynesian sauce.",
  },
  {
    price: 38.41,
    id: 16,
    name: 'Cheesy Gordita Crunch',
    imageUrl: '/img/shop/shop/cheesy-gordita-crunch.webp',
    hasFreeShipping: true,
    hasDiscount: false,
    discount: 0,
    stock: 220,
    promotion: [],
    categories: ['Fast food'],
    region: ['Europe'],
    rating: 1.39,
    payment: ['In 6 installments', 'In cash'],
    description:
      'An effective fast-food experience hinges on texture. Mouthfeel. Most fast food is rough and salty or mushy and gelatinous. But rarely the twain shall meet in one package.',
  },
];
